# Generated by Django 3.0.5 on 2020-04-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200421_0626'),
        ('users', '0004_auto_20200421_1102'),
    ]

    operations = [
    ]
