# Generated by Django 3.0.5 on 2020-04-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200420_1332'),
        ('users', '0005_user_signup_confirmation'),
    ]

    operations = [
    ]
