# Generated by Django 3.0.5 on 2020-04-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20200421_1314'),
        ('users', '0005_merge_20200421_1110'),
    ]

    operations = [
    ]
