# Generated by Django 3.0.5 on 2020-04-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20200421_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featureing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
