# Generated by Django 3.0.5 on 2020-04-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_project_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project_tags',
        ),
    ]
