# Generated by Django 3.0.5 on 2020-04-20 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200420_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^0(10|11|12|15)\\d{8}$', message='please enter egyptian mobile phone: like= 01012345678')]),
        ),
    ]
