# Generated by Django 3.0.5 on 2020-04-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_project_tags'),
        ('users', '0008_auto_20200421_1746'),
    ]

    operations = [
    ]
