# Generated by Django 3.0.5 on 2020-04-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_is_staff'),
        ('users', '0009_merge_20200421_1952'),
    ]

    operations = [
    ]
