# Generated by Django 3.0.5 on 2020-04-29 17:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200426_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='details',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
