# Generated by Django 3.0.5 on 2020-04-30 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200429_1742'),
        ('users', '0016_comment_created_at'),
    ]

    operations = [
    ]
