# Generated by Django 3.0.5 on 2020-04-30 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200430_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_target',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
